version: '3.1'

services:
  ubuntu:
    build: ./Ubuntu
    stdin_open: true
    image: annayemets/docker_exam-ubuntu:latest

  web:
    build: ./Nginx
    ports:
      - 8080:80
    image: annayemets/docker_exam-web:latest 
